# Generated by Django 2.2.15 on 2020-09-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=50)),
                ('index_1', models.CharField(max_length=50)),
                ('index_2', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
                ('cage', models.CharField(max_length=50)),
                ('sample_type', models.CharField(max_length=50)),
                ('orgin_diet', models.CharField(max_length=50)),
            ],
        ),
    ]
