# Generated by Django 2.2.15 on 2020-09-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtuTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=100)),
                ('sa_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.MetaDataTable')),
            ],
        ),
    ]
