# Generated by Django 2.2.15 on 2020-09-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200909_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otutable',
            name='sa_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_14',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_15',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='sa_9',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='otutable',
            name='seq',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
