# Generated by Django 2.2.15 on 2020-09-09 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200909_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomictable',
            name='seq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomics', to='app.OtuTable'),
        ),
    ]
