# Generated by Django 2.2.15 on 2020-10-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amoel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otutable',
            old_name='hash',
            new_name='table_hash',
        ),
    ]
