# Generated by Django 2.2.15 on 2020-10-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amoel', '0003_auto_20201001_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otu_metad_id',
            old_name='otu_hash',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='otutable',
            old_name='tab_hash',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='reference_sequence',
            old_name='ref_hash',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='taxonomic',
            old_name='tax_hash',
            new_name='hash',
        ),
    ]
