# Generated by Django 2.2.15 on 2020-10-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amoel', '0005_auto_20201001_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomic',
            name='hash',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amoel.OtuTable'),
        ),
    ]
